# Generated by Django 4.2.7 on 2023-11-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=10)),
                ('date', models.DateField(null=True)),
                ('time', models.CharField(max_length=10)),
                ('number_of_people', models.DecimalField(decimal_places=0, max_digits=10)),
                ('message', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Guest',
                'verbose_name_plural': 'Guests',
                'ordering': ['name'],
            },
        ),
    ]
